---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Chart.Version }}
  name: {{ template "fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        provider: fabric8
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        version: 1.0.0
    spec:
      containers:
      - image: "{{ .Values.appimage.image.name }}:{{ .Values.appimage.image.tag }}"
        livenessProbe:
          initialDelaySeconds: 60
          tcpSocket:
            port: 80
        env:
          - name: test
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: test
        name: {{ .Values.appimage.image.displayName }}
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
        securityContext:
          privileged: false