apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Chart.Version }}
  name: {{ template "fullname" . }}
  annotations:
    avp.kubernetes.io/path: bansira
type: Opaque
data:
  test: {{ template "test" . }}